# Site settings
name: Daily Notes
email: jandster@gmail.com
author: Jand Lin
url: https://860660.xyz
resume_site: https://860660.xyz
github: https://github.com/jandster/
baseurl: "/"
description: Work is the Work!
meta_description: Jand Lin;个人博客;
motto: Talk is cheap, show me the code.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: jandster

# Build settings
markdown: kramdown

baidu_analysis: 6c1a9b38c10903ec3ccb84d48759fceb
revolvermaps: 59wdl4sx2vf
